// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dRBehCdEJhGHDmq2SpUGoD
// Component: b8ewyzpY3SVG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: vm52jR6x2QsO/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: dRBehCdEJhGHDmq2SpUGoD/projectcss
import sty from "./PlasmicHeroTitle.module.css"; // plasmic-import: b8ewyzpY3SVG/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: JYoq77I0bguk/icon

createPlasmicElementProxy;

export type PlasmicHeroTitle__VariantMembers = {};
export type PlasmicHeroTitle__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeroTitle__VariantsArgs;
export const PlasmicHeroTitle__VariantProps = new Array<VariantPropType>();

export type PlasmicHeroTitle__ArgsType = {};
type ArgPropType = keyof PlasmicHeroTitle__ArgsType;
export const PlasmicHeroTitle__ArgProps = new Array<ArgPropType>();

export type PlasmicHeroTitle__OverridesType = {
  frame10?: Flex__<"div">;
  frame9?: Flex__<"div">;
  frame8?: Flex__<"div">;
  frame7?: Flex__<"div">;
  button?: Flex__<typeof Button>;
};

export interface DefaultHeroTitleProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHeroTitle__RenderFunc(props: {
  variants: PlasmicHeroTitle__VariantsArgs;
  args: PlasmicHeroTitle__ArgsType;
  overrides: PlasmicHeroTitle__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"frame10"}
      data-plasmic-override={overrides.frame10}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.frame10
      )}
    >
      <div
        data-plasmic-name={"frame9"}
        data-plasmic-override={overrides.frame9}
        className={classNames(projectcss.all, sty.frame9)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"frame8"}
          data-plasmic-override={overrides.frame8}
          hasGap={true}
          className={classNames(projectcss.all, sty.frame8)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__fqbEl
            )}
          >
            {"Web3 gaming"}
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"frame7"}
          data-plasmic-override={overrides.frame7}
          hasGap={true}
          className={classNames(projectcss.all, sty.frame7)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vLw3B
            )}
          >
            {"for"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__wqUNm
            )}
          >
            {"everyone."}
          </div>
        </Stack__>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__ku1G5
        )}
      >
        {
          "Grid is a secure, low-cost, gamer-friendly Ethereum L2, designed to bring the next billion gamers onchain."
        }
      </div>
      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        className={classNames("__wab_instance", sty.button)}
        color={"blue"}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__jJFbS
          )}
        >
          {"Bridge your assets"}
        </div>
      </Button>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame10: ["frame10", "frame9", "frame8", "frame7", "button"],
  frame9: ["frame9", "frame8", "frame7"],
  frame8: ["frame8"],
  frame7: ["frame7"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  frame10: "div";
  frame9: "div";
  frame8: "div";
  frame7: "div";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeroTitle__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeroTitle__VariantsArgs;
    args?: PlasmicHeroTitle__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeroTitle__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHeroTitle__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeroTitle__ArgProps,
          internalVariantPropNames: PlasmicHeroTitle__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeroTitle__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame10") {
    func.displayName = "PlasmicHeroTitle";
  } else {
    func.displayName = `PlasmicHeroTitle.${nodeName}`;
  }
  return func;
}

export const PlasmicHeroTitle = Object.assign(
  // Top-level PlasmicHeroTitle renders the root element
  makeNodeComponent("frame10"),
  {
    // Helper components rendering sub-elements
    frame9: makeNodeComponent("frame9"),
    frame8: makeNodeComponent("frame8"),
    frame7: makeNodeComponent("frame7"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicHeroTitle
    internalVariantProps: PlasmicHeroTitle__VariantProps,
    internalArgProps: PlasmicHeroTitle__ArgProps
  }
);

export default PlasmicHeroTitle;
/* prettier-ignore-end */
